### ISSUE TITLE
Error while trying to read array with spark

### ISSUE THREAD

**Issue by royassis** [TileDB-Inc/TileDB-Spark#115]
Hey

I'm trying to start with with tilebd-spark. I've managed to write and read an array from disk. But i'm having an issue with issue
with reading an array written with tiledb-py.

I;m getting this error:
```
Unsupported TileDB to Spark DataFrame type mapping for schema column '__tiledb_rows': TILEDB_UINT64
```

Is there a solution ?

**Comment by DimitrisStaratzis** [comment]
Hi @royassis,

The problem is that you are trying to read an array which has an attribute/dimension of type: `UINT_64` which is not supported by TileDB-Spark. Please have a look at the README and more specifically the "type_mapping" section for more details.  [https://github.com/TileDB-Inc/TileDB-Spark#type-mapping](https://github.com/TileDB-Inc/TileDB-Spark#type-mapping).

To solve the problem you need to change the datatype of the "__tiledb_rows" dimension/attribute to a supported type (e.g `INT_64`)

**Comment by royassis** [comment]
Is it possible to change a dimension dtype after creation ?

**Comment by DimitrisStaratzis** [comment]
Although it is not possible to directly change the attribute/dimension type, you can instead use the SchemaEvolution feature as shown in one of our tests here: https://github.com/TileDB-Inc/TileDB-Py/blob/dev/tiledb/tests/test_schema_evolution.py

Use the drop_attribute() and add_attribute() methods.

**Comment by ihnorton** [comment]
Hi @royassis, we will see what we can do regarding uint64 here for the longer-term...

For now, since it looks like you are using `tiledb.from_csv/from_pandas`, in the meantime a work-around is to ingest the data with an int64 index:

Given `sample.csv`
```
row,a,b,c,d,e
0,0,1,2,3,4
1,10,11,12,13,14
2,20,21,22,23,24
3,30,31,32,33,34
4,40,41,42,43,44
5,50,51,52,53,54
6,60,61,62,63,64
7,70,71,72,73,74
8,80,81,82,83,84
```

Here's an example which will give an int64 dimension:

```
import tiledb, tempfile, numpy as np, pandas as pd
uri = tempfile.mkdtemp()

df = pd.read_csv("sample.csv", dtype={"row": "int64"})
df.set_index("row", inplace=True)

print("df.row dtype: ", df.index.dtype)

tiledb.from_pandas(uri, df)
a = tiledb.open(uri)

print("uri is: ", uri,)
print("schema is: ", a.schema)
```

schema:
```
df.row dtype:  int64
schema is:  ArraySchema(
  domain=Domain(*[
    Dim(name='row', domain=(0, 8), tile=8, dtype='int64', filters=FilterList([ZstdFilter(level=-1), ])),
  ]),
  attrs=[
    Attr(name='a', dtype='int64', var=False, nullable=False, filters=FilterList([ZstdFilter(level=-1), ])),
    Attr(name='b', dtype='int64', var=False, nullable=False, filters=FilterList([ZstdFilter(level=-1), ])),
    Attr(name='c', dtype='int64', var=False, nullable=False, filters=FilterList([ZstdFilter(level=-1), ])),
    Attr(name='d', dtype='int64', var=False, nullable=False, filters=FilterList([ZstdFilter(level=-1), ])),
    Attr(name='e', dtype='int64', var=False, nullable=False, filters=FilterList([ZstdFilter(level=-1), ])),
  ],
  cell_order='row-major',
  tile_order='row-major',
  capacity=10000,
  sparse=False,
)
```

**Comment by royassis** [comment]
Thank you very much @ihnorton
